services:
  app:
    image: ghcr.io/houbou98-19/barcode-shopping:latest
    pull_policy: always
    ports:
      - "8080:5000"
    volumes:
      - shopping_data:/data
    restart: unless-stopped

volumes:
  shopping_data:
